<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sonias-MacBook-Pro.local" ignored="0" name="Default test" tests="5" failures="1" timestamp="27 Jun 2018 03:21:27 GMT" time="16.072" errors="0">
  <testcase name="verifyTitle" time="0.092" classname="mockaroo.MockarooDataValidation"/>
  <testcase name="verifyHeader" time="0.383" classname="mockaroo.MockarooDataValidation"/>
  <testcase name="verifyTableHeader" time="0.25" classname="mockaroo.MockarooDataValidation"/>
  <testcase name="creatingFields" time="10.954" classname="mockaroo.MockarooDataValidation"/>
  <testcase name="verifyDownloadedData" time="0.001" classname="mockaroo.MockarooDataValidation">
    <failure type="java.io.FileNotFoundException" message="C:/Users/obeyd/Downloads/MOCK_DATA.csv (No such file or directory)">
      <![CDATA[java.io.FileNotFoundException: C:/Users/obeyd/Downloads/MOCK_DATA.csv (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at java.io.FileReader.<init>(FileReader.java:58)
at mockaroo.MockarooDataValidation.loadLists(MockarooDataValidation.java:194)
at mockaroo.MockarooDataValidation.verifyDownloadedData(MockarooDataValidation.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyDownloadedData -->
</testsuite> <!-- Default test -->
